[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3

[tool.mypy]
python_version = "3.6"
warn_return_any = true
warn_unused_configs = true
files = "pytest_bdd/**/*.py"

[[tool.mypy.overrides]]
module = ["parse", "parse_type", "glob2"]
ignore_missing_imports = true
